<?php
/**
 * @file
 * Module's main file, general definitions and hooks.
 */


/**
 * Implements hook_help().
 */
function menu_export_help($path, $arg) {
  switch ($path) {
    case 'admin/help#menu_export':
      return '<p>' . t("Menu Export is a Drupal 7 module to export menus easily.") . '</p>';
  }
}

/**
 * Implements hook_permission().
 */
function menu_export_permission() {
  return array(
    'administer menu export' => array(
      'title' => t('Administer menu exporter'),
    ),
    'administer menu import' => array(
      'title' => t('Administer menu importer'),
      'description' => t('Warning: Give to trusted roles only; this permission has security implications.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function menu_export_menu() {
  $items = array();

  $items['admin/config/system/menu_export'] = array(
    'title' => 'Menu export',
    'description' => 'Used to export menu into file',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('menu_export_list_export_form'),
    'access arguments' => array("administer menu export"),
    'weight' => 11,
  );

  $items['admin/structure/menu/manage/%/export'] = array(
    'title' => 'Export',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('menu_export_export_form', 4),
    'access arguments' => array("administer menu export"),
    'type' => MENU_LOCAL_TASK,
    'weight' => 11,
  );

  $items['admin/structure/menu/import'] = array(
    'title' => 'Import',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('menu_export_import_form'),
    'access arguments' => array("administer menu import"),
    'type' => MENU_LOCAL_TASK,
    'weight' => 11,
  );

  return $items;
}

/**
 * List of all module for the export.
 */
function menu_export_list_export_form($form, &$form_state) {
  $form['menu'] = array(
    '#type' => 'select',
    '#title' => t("Choose a menu to export"),
    '#options' => menu_get_menus(),
  );

  $form['submit'] = array('#type' => 'submit', '#value' => t('Export'));

  return $form;
}

/**
 * Submit function.
 */
function menu_export_list_export_form_submit($form, &$form_state) {
  $menu_name = $form_state['values']['menu'];
  drupal_goto("admin/structure/menu/manage/" . $menu_name . "/export");
}

/**
 * Display the export.
 */
function menu_export_export_form($form, &$form_state, $menu_name) {
  $elements = menu_tree_all_data($menu_name);
  $menu = menu_load($menu_name);

  ob_start();
  echo '$menu = new StdClass();' . "\n";
  foreach ($menu as $k => $v) {
    echo '$menu->' . $k . ' = "' . addslashes($v) . '";' . "\n";
  }
  echo '$menu->items = array();' . "\n";
  _menu_export_parse_menu($elements, '$menu->items');

  $out = ob_get_clean();

  $form['export'] = array(
    '#type' => 'textarea',
    '#title' => check_plain("Export of «" . $menu['title'] . "»"),
    '#default_value' => $out,
    '#rows' => 30,
  );

  return $form;
}

/**
 * Display the import.
 */
function menu_export_import_form($form, &$form_state) {
  $form['import'] = array(
    '#type' => 'textarea',
    '#title' => 'Paste menu code here',
    '#rows' => 30,
  );

  $form['submit'] = array('#type' => 'submit', '#value' => t('Import'));

  return $form;
}

/**
 * Submit function.
 */
function menu_export_import_form_submit($form, &$form_state) {
  $code = _menu_export_sanitize_string($form_state['values']['import']);

  // eval() function has known security risk.
  // $code variable passed is previously sanitised
  // and exclusive permission added.
  ob_start();
  // @ignore security_19 1
  eval($code);
  ob_end_clean();

  if (!empty($menu) && is_object($menu)) {
    if (menu_export_menu_import($menu)) {
      drupal_set_message(t('Menu correctly imported'));
      $form_state['redirect'] = "admin/structure/menu/manage/" . $menu->menu_name;
    }
    else {
      drupal_set_message(t('The menu already exists.'), 'error');
    }
  }
  else {
    drupal_set_message(t('An error occurred and processing did not complete.'), 'error');
  }
}

/**
 * Internal function used for display one item.
 */
function _menu_export_parse_menu($elements, $key) {
  $i = 0;
  foreach ($elements as $element) {
    echo "\n";
    echo $key . '[' . $i . '] = new StdClass();' . "\n";
    echo $key . '[' . $i . ']->label = "' . addslashes($element['link']['title']) . '";' . "\n";
    echo $key . '[' . $i . ']->path = "' . $element['link']['href'] . '";' . "\n";
    echo $key . '[' . $i . ']->weight = ' . $i . ';' . "\n";

    if (!empty($element['below'])) {
      echo $key . '[' . $i . ']->items = array();' . "\n";
      _menu_export_parse_menu($element['below'], $key . '[' . $i . ']->items');
    }
    $i++;
  }
}

/**
 * Tool to import menu exported previously.
 *
 * @param StdClass $menu
 *   Object created by the export.
 */
function menu_export_menu_import(StdClass $menu) {
  $list_of_menus = menu_get_menus();
  if (!isset($list_of_menus[$menu->menu_name])) {
    $elem = array(
      "menu_name" => $menu->menu_name,
      "title" => $menu->title,
      "description" => $menu->description,
    );

    menu_save($elem);
    if (!empty($menu->items)) {
      _menu_export_menu_import_menu_item($menu->menu_name, $menu->items);
    }
    return TRUE;
  }
  return FALSE;
}

/**
 * Internal function used by menu_export_menu_import() to save one link item.
 */
function _menu_export_menu_import_menu_item($menu_name, $items, $plid = 0) {
  foreach ($items as $item) {
    $elem = array(
      "link_path" => $item->path,
      "link_title" => $item->label,
      "menu_name" => $menu_name,
      "weight" => (integer) $item->weight,
      "plid" => $plid,
    );
    $mlid = menu_link_save($elem);
    if (!empty($item->items)) {
      _menu_export_menu_import_menu_item($menu_name, $item->items, $mlid);
    }
  }
}

/**
 * Internal function used to sanitize.
 */
function _menu_export_sanitize_string($code) {
  $safe_string = array();
  $string = explode("\n", $code);
  foreach ($string as $s) {
    $check = trim($s);

    $test = array(
      (strpos($check, '$menu') === 0),
      (substr_count($check, ';') === 1),
      (strcmp(substr($check, -1), ';') === 0),
    );

    if ($test[0] && $test[1] && $test[2]) {
      $safe_string[] = $check;
    }
  }
  return implode($safe_string, "\n");
}
